console.log("=================")
console.log("   Whataburger   ")
console.log("-----------------")
console.log("  Order Details  ")
console.log("-----------------")
console.log("Item Quantity Price")
console.log("-----------------")
console.log("Cookie 1 4.99    ")
console.log("Soda 1 2.99      ")
console.log("-----------------")
console.log("Total  10.99     ")
console.log("=================")